---
# Source: global-argocd-app/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mock-authentication-dev
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: dev
  project: default
  source:
    repoURL: 
    path: 
    targetRevision: feature/A213
    helm:
      releaseName: mock-authentication-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
