---
# Source: global-argocd-app/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mock-authentication-ndev
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: ndev
  project: default
  source:
    repoURL: 'https://github.com/BENMALEKarim/helm-charts/'
    path: 'apps/mock-authentication'
    targetRevision: develop
    helm:
      valueFiles:
        - '/environments/ndev-values.yaml'
        - '/apps/mock-authentication/environments/ndev-values.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
