---
# Source: global-argocd-app/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mock-authentication-cdev
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: cdev
  project: default
  source:
    repoURL: 'https://github.com/BENMALEKarim/helm-charts/'
    path: 'apps/mock-authentication'
    targetRevision: master
    helm:
      valueFiles:
        - '/environments/cdev-values.yaml'
        - '/apps/mock-authentication/environments/cdev-values.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
