apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- if eq .Values.environment "dev" }}
  name: {{ .Values.appName }}-{{ .Values.formattedBranch }}-{{ .Values.environment }}
  {{- else }}
  name: {{ .Values.appName }}-{{ .Values.environment }}
  {{- end }}
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: {{ .Release.Namespace }}
  project: default
  source:
    repoURL: 'https://github.com/BENMALEKarim/helm-charts/'
    path: 'apps/{{ .Values.appName }}'
    targetRevision: {{ .Values.branch }}
    helm:
      valueFiles:
        - '/environments/{{ .Values.environment }}-values.yaml'
        - '/apps/{{ .Values.appName }}/environments/{{ .Values.environment }}-values.yaml'
      {{- if eq .Values.environment "dev" }}
      valuesObject:
        appName: {{ .Values.appName }}-{{ .Values.formattedBranch }}
      {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
