apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appName }}-{{ .Values.environment }}
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: {{ .Release.namespace }}
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: {{ .Values.path }}
    targetRevision: {{ .Values.branch }}
    helm:
      releaseName: {{ .Values.appName }}-{{ .Values.environment }}
      {{- if ne .Values.environment "dev" }}
      valueFiles:
        - '/environments/{{ .Values.environment }}-values.yaml'
        - '/apps/{{ .Values.appName }}/environments/{{ .Values.environment }}-values.yaml'
      {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
