apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appName }}-dev
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: {{ .Values.namespace }}
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: helm/
    targetRevision: {{ .Values.branch }}
    helm:
      releaseName: {{ .Values.appName }}-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
