{{- range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ . }}-{{ $.Values.environment }}
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: {{ $.Values.namespace }}
  project: default
  source:
    repoURL: 'https://github.com/BENMALEKarim/helm-charts/'
    path: 'apps/{{ . }}'
    {{- if or (eq $.Values.environment "prod") (q $.Values.environment "pps") }}
    targetRevision: {{ $.Values.release }}
    {{- else }}
    targetRevision: 'master'
    {{- end }}
    helm:
      valueFiles:
        - '/environments/{{ $.Values.environment }}-values.yaml'
        - '/apps/{{ . }}/environments/{{ $.Values.environment }}-values.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
{{ end }}
