name: Refresh ArgoCD Application files

on:
  workflow_dispatch:
    inputs:
        production_release:
          description: Production Release
          required: true

jobs:
  refresh-argocd:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ inputs.production_release }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Generate Helm Templates
      run: |
        for file in environments/*.yaml; do
          if [ "$file" != "environments/prod-values.yaml" ]; then
            env=$(basename $file .yaml | cut -d'-' -f1)
            output_file="$env-argocd.yaml"
            helm template test --values $file argocd-application-chart > argocd/nonprod/$output_file
          fi
        done
        mkdir -p argocd/prod
        helm template test --values environments/prod-values.yaml --set release=${{ env.RELEASE_TAG }} argocd-application-chart > argocd/prod/prod-argocd.yaml

    - name: Commit and Push Changes
      run: |
        git config user.email ${{ secrets.REPOSITORY_EMAIL }}
        git config user.name ${{ secrets.REPOSITORY_USER }}
        git add .
        git commit -m "Refresh ArgoCD application files" || exit 0
        git push https://${{ secrets.REPOSITORY_TOKEN }}@github.com/BENMALEKarim/argocd-apps.git

  
